name: ğŸš€ Pull Request Title Validation âœ…

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  validate_pull_request_title:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ” Validate PR Title Format
        uses: amannn/action-semantic-pull-request@v5.3.0
        with:
          types: |
            feat
            fix
          headerPattern: '^(\w+)\(fase\d+\): (.+)$'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}